### ISSUE TITLE
can I see a sample ppt you created via gpt?

### ISSUE THREAD

**Issue by AbubakrChan** [AmNotAGoose/Python-PPTX-ChatGPT-Presentation-Generator#2]
Hey 

can I see a sample ppt you created via gpt?

Thank you

**Comment by AmNotAGoose** [comment]
Sure, here's a presentation about Among Us

[Sussy Among Us.pptx](https://github.com/AmNotAGoose/Python-PPTX-ChatGPT-Presentation-Generator/files/12571426/Sussy.Among.Us.pptx)

**Comment by AmNotAGoose** [comment]
I've also added another example under /examples :D
